import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Themeprovider";
import Navbar from "@/components/navbar";
import ProgessBar from "@/components/progessBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ProgessBar/>
            <Navbar/>
            <main className="px-5 py-5 sm:px-28 sm:py-5">
        {children}
            </main>

        </ThemeProvider>
        </body>
    </html>
  );
}
